# Generated by Django 5.2.10 on 2026-01-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('chief', 'Chief'), ('admin', 'Admin')], max_length=20)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='new/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='new/')),
                ('tags', models.CharField(help_text='Comma separated tags', max_length=255)),
            ],
            options={
                'db_table': 'Admin_table',
            },
        ),
    ]
