# Generated by Django 5.2.10 on 2026-01-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='admin',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='admins/banners/'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admins/profile/'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin_table',
        ),
    ]
