# Generated by Django 5.2.10 on 2026-01-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0002_alter_admin_options_alter_admin_banner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterField(
            model_name='admin',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='new/'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='new/'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin_table',
        ),
    ]
