# Generated by Django 5.2.10 on 2026-01-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0003_alter_admin_options_alter_admin_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='tags',
        ),
    ]
