# Generated by Django 5.2.10 on 2026-01-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0005_usercard_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chief', 'Chief'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
