# Generated by Django 5.2.10 on 2026-01-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0006_usercard_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('banner_image', models.ImageField(upload_to='banners/')),
                ('role', models.CharField(choices=[('headstaff', 'Head Staff'), ('girlowner', 'Girl Owner'), ('member', 'Member')], default='member', max_length=10)),
                ('friendly', models.BooleanField(default=False)),
                ('active_voice_channel', models.BooleanField(default=False)),
                ('active_message', models.BooleanField(default=False)),
                ('moderator', models.BooleanField(default=False)),
                ('ticket_manager', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Head_Staff',
            },
        ),
    ]
