# Generated by Django 5.2.10 on 2026-01-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0007_headstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headstaff',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='headstaff',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='headstaff',
            name='role',
            field=models.CharField(choices=[('headstaff', 'Head Staff'), ('girlowner', 'Girl Owner'), ('girlmanager', 'Girl Manager'), ('member', 'Member')], default='member', max_length=15),
        ),
    ]
