# Generated by Django 5.2.10 on 2026-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0008_alter_headstaff_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('banner_image', models.ImageField(upload_to='banners/')),
                ('friendly', models.BooleanField(default=False)),
                ('active_voice_channel', models.BooleanField(default=False)),
                ('active_message', models.BooleanField(default=False)),
                ('moderator', models.BooleanField(default=False)),
                ('ticket_manager', models.BooleanField(default=False)),
                ('manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Artist_Card',
            },
        ),
    ]
