# Generated by Django 5.2.10 on 2026-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0009_artistcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistcard',
            name='artist_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
