# Generated by Django 5.2.10 on 2026-01-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0011_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
