# Generated by Django 5.2.10 on 2026-02-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0012_staff_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('chief', 'Chief'), ('high_court', 'High Court'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
