# Generated by Django 5.2.10 on 2026-02-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0013_alter_usercard_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeFireTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_head', models.CharField(max_length=200)),
                ('team_elders', models.TextField(help_text='Separate names using · or commas')),
                ('team_members', models.TextField(help_text='Separate names using · or commas')),
                ('guild_id', models.CharField(default='923838382', editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Free Fire Team',
                'verbose_name_plural': 'Free Fire Team',
                'db_table': 'free_fire_team',
            },
        ),
    ]
