# Generated by Django 5.2.10 on 2026-02-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ram_rajya', '0014_freefireteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freefireteam',
            name='guild_id',
            field=models.CharField(default='3048559701', editable=False, max_length=20),
        ),
    ]
